server:
  port: 80
  context-path: /uam

logging.level.root: info

#设置session存储类型为redis
spring:
  session:
    store-type: redis

# 配置redis连接信息
spring.redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    pool:
      max-idle: 1
      max-wait: 10


#spring的数据源配置
spring.datasource:
  url: jdbc:mysql://localhost:3306/uam
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver

spring.jpa:
  database: mysql
  show-sql: true
  hibernate.ddl-auto: update
  hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# session的过期时间，单位是分钟   1440表示1天
sessiontimeout: 1440

# cookie的过期时间，单位是秒  86400表示1天
cookietimeout: 86400
